# NumPy Tutorial @ EuroSciPy 2019

https://github.com/leriomaggio/numpy-euroscipy

In [100]:
!git clone https://github.com/leriomaggio/numpy-euroscipy

Cloning into 'numpy-euroscipy'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 197 (delta 44), reused 77 (delta 34), pack-reused 103
Receiving objects: 100% (197/197), 3.59 MiB | 1.99 MiB/s, done.
Resolving deltas: 100% (90/90), done.


## numpy arrays 

In [1]:
import numpy as np  # naming import convention
np.__version__

'1.17.1'

In [2]:
np.array?

In [4]:
r = range(10)
def printit(it): print(list(it))
    
printit(r)

print(type(r))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'range'>


In [9]:
ra = np.arange(10) 
print(ra,type(ra),ra.dtype)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int64


In [8]:
raf = np.arange(0, 10, 1.0)
print(raf,type(raf),raf.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] <class 'numpy.ndarray'> float64


In [11]:
print(f"dtype of 'ra': {ra.dtype}, dtype of 'raf': {raf.dtype}")

dtype of 'ra': int64, dtype of 'raf': float64


In [15]:
print(ra.itemsize,ra.nbytes,ra.ndim,ra.shape,ra.dtype)
print(raf.itemsize,raf.nbytes,raf.ndim,raf.shape,raf.dtype)

8 80 1 (10,) int64
8 80 1 (10,) float64


## np.linspace and np.logspace

In [16]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [17]:
np.logspace(0, np.e**2, 10, base=np.e)

array([1.00000000e+00, 2.27278564e+00, 5.16555456e+00, 1.17401982e+01,
       2.66829540e+01, 6.06446346e+01, 1.37832255e+02, 3.13263169e+02,
       7.11980032e+02, 1.61817799e+03])

## Random Number Generation

In [18]:
# uniform random numbers in [0,1]
ru = np.random.rand(10)
# standard normal distributed random numbers
rs = np.random.randn(10)
print(ru)
print(rs)

[0.21171616 0.83170234 0.794121   0.8678432  0.95199737 0.54872379
 0.99377429 0.72533863 0.21197336 0.24448801]
[-0.52418294 -0.07696394 -1.3414668   1.00035989  0.74325208  1.4849636
  1.63444992  1.38099827  1.6152489   0.16817057]


In [20]:
print(np.random.rand(10))
print(np.random.rand(10))

[0.8617346  0.73068189 0.08267689 0.83187989 0.77584124 0.33942481
 0.84003325 0.77282938 0.30471154 0.15049156]
[0.70213459 0.82153638 0.76217322 0.67712871 0.70917922 0.80436686
 0.7728266  0.56574216 0.17778415 0.98211681]


In [22]:
np.random.seed(1234)
print(np.random.rand(10))
print(np.random.rand(10))

[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581 0.27259261
 0.27646426 0.80187218 0.95813935 0.87593263]
[0.35781727 0.50099513 0.68346294 0.71270203 0.37025075 0.56119619
 0.50308317 0.01376845 0.77282662 0.88264119]


In [23]:
np.random.seed(1234)
print(np.random.rand(10))
print(np.random.rand(10))

[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581 0.27259261
 0.27646426 0.80187218 0.95813935 0.87593263]
[0.35781727 0.50099513 0.68346294 0.71270203 0.37025075 0.56119619
 0.50308317 0.01376845 0.77282662 0.88264119]


## Zeros and Ones (or Empty)

In [24]:
Z = np.zeros((3,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
O = np.ones((3, 3))
print(O)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
E = np.empty(10)
print(E)

[0.35781727 0.50099513 0.68346294 0.71270203 0.37025075 0.56119619
 0.50308317 0.01376845 0.77282662 0.88264119]


## Diagonal Matrices

## Create numpy.ndarray from list

In [31]:
v = np.array([1,2,3,4])
print(v,type(v))

[1 2 3 4] <class 'numpy.ndarray'>


In [32]:
v = np.asarray([1, 2, 3, 4])
print(v,type(v))

[1 2 3 4] <class 'numpy.ndarray'>


In [39]:
v = np.asarray(range(4))
print(v,type(v))

[0 1 2 3] <class 'numpy.ndarray'>


In [40]:
v = np.asarray([[1, 2],[3, 4]])
print(v,type(v))
v

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


array([[1, 2],
       [3, 4]])

In [41]:
v = np.asarray([[1, 2],[3, 4, 5]])
print(v,type(v))
v

[list([1, 2]) list([3, 4, 5])] <class 'numpy.ndarray'>


array([list([1, 2]), list([3, 4, 5])], dtype=object)

## Vectorization & Times...

In [42]:
L = range(100000)

In [43]:
%timeit [i**2 for i in L]

30.8 ms ± 1.59 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [49]:
a = np.asarray(range(100000))
%timeit a**2  # This operation is called Broadcasting - more on this later!

71.1 µs ± 2.51 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [50]:
a = np.arange(100000)
%timeit a**2  # This operation is called Broadcasting - more on this later!

67.8 µs ± 76.6 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [45]:
%timeit [element**2 for element in a]

34.8 ms ± 75.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Data vs Metadata (Attributes)

In [51]:
a = np.arange(45)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [52]:
a.shape

(45,)

In [56]:
# new object, SAME data!!!
A = a.reshape(9, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [57]:
A.shape

(9, 5)

In [61]:
a[3]=0
a[3]

0

In [60]:
A[0,3]

0

In [63]:
n, m = A.shape
B = A.reshape((1,n*m))
B

array([[ 0,  1,  2,  0,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

## Flatten

In [64]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.ravel()

array([1, 2, 3, 4, 5, 6])

In [65]:
A.ravel('F')  # order F (Fortran) is column-major, C (default) row-major

array([1, 4, 2, 5, 3, 6])

In [66]:
# this function create a copy of the data
A.flatten()

array([1, 2, 3, 4, 5, 6])

## Introducing np.newaxis

In [68]:
A = np.arange(20).reshape(10, 2)
A = A[np.newaxis, ...]  # this is called ellipsis

print(A)
print(A.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]] (1, 10, 2)


## Custom dtype

In [71]:
rt = np.dtype([('name', np.str_, 40), ('numitems', np.int32), ('price', np.float32)])

In [72]:
print(rt['name'], rt['numitems'], rt['price'])

<U40 int32 float32


In [74]:
record_items = np.array([('Meaning of life DVD', 42, 3.14), ('Butter', 13, 2.72)], 
                        dtype=rt)

In [75]:
print(record_items)

[('Meaning of life DVD', 42, 3.14) ('Butter', 13, 2.72)]


## Indexing

## Vectorisation and Broadcasting

In [76]:
def Theta(x):
    """
    Scalar implemenation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [78]:
Theta(np.array([-3,-2,-1,0,1,2,3]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [79]:
Theta_vec = np.vectorize(Theta)
Theta_vec(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

## Broadcasting

In [90]:
D = np.random.rand(100000, 10)
adj = np.random.rand(10)

In [91]:
%%timeit
#Naive Solution

# Create a new array filled with zeros, of the same shape as macros.
result = np.zeros_like(D)

# Now multiply each row of macros by cal_per_macro. In Numpy, `*` is
# element-wise multiplication between two arrays.
for i in range(D.shape[0]):
    result[i, :] = D[i, :] * adj
    
result

154 ms ± 10.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [92]:
%%timeit 
#Using np.tile

adj_stretch = np.tile(adj, (D.shape[0], 1))

D * adj_stretch

1.87 ms ± 4.71 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [93]:
%%timeit
# Broadcasting

D * adj  

1.61 ms ± 5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Fancy indexing

In [101]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [102]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [103]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([11, 22, 34])

In [108]:
b = A.flatten()
b

array([ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [110]:
#broadcasting
b>17

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [111]:
b[b>17]

array([20, 21, 22, 23, 24, 30, 31, 32, 33, 34, 40, 41, 42, 43, 44])

## Copy and "deep copy" 

In [122]:
A = np.array([[1, 2], [3, 4]])
B = A[0,:]
B[0] = 100
print(A)
print(B)

[[100   2]
 [  3   4]]
[100   2]


In [115]:
def aid(x):
    # This function returns the memory
    # block address of an array.
    return x.__array_interface__['data'][0]

In [117]:
A = np.array([[1, 2], [3, 4]])
# now B is referring to the same array data as A 
B = A 
aid(A) == aid(B)

True

In [118]:
B = np.copy(A)
aid(A) == aid(B)

False

## NumPy Seralisation and I/O --> Pandas

In [125]:
!head numpy-euroscipy/stockholm_td_adj.dat

Year Month Day T_6 T12 T18 Valid 
1800  1  1    -6.1    -6.1    -6.1 1
1800  1  2   -15.4   -15.4   -15.4 1
1800  1  3   -15.0   -15.0   -15.0 1
1800  1  4   -19.3   -19.3   -19.3 1
1800  1  5   -16.8   -16.8   -16.8 1
1800  1  6   -11.4   -11.4   -11.4 1
1800  1  7    -7.6    -7.6    -7.6 1
1800  1  8    -7.1    -7.1    -7.1 1
1800  1  9   -10.1   -10.1   -10.1 1


In [131]:
data = np.genfromtxt('numpy-euroscipy/stockholm_td_adj.dat', skip_header=1)
data.shape

(77431, 7)

In [132]:
data[:5,:]

array([[ 1.80e+03,  1.00e+00,  1.00e+00, -6.10e+00, -6.10e+00, -6.10e+00,
         1.00e+00],
       [ 1.80e+03,  1.00e+00,  2.00e+00, -1.54e+01, -1.54e+01, -1.54e+01,
         1.00e+00],
       [ 1.80e+03,  1.00e+00,  3.00e+00, -1.50e+01, -1.50e+01, -1.50e+01,
         1.00e+00],
       [ 1.80e+03,  1.00e+00,  4.00e+00, -1.93e+01, -1.93e+01, -1.93e+01,
         1.00e+00],
       [ 1.80e+03,  1.00e+00,  5.00e+00, -1.68e+01, -1.68e+01, -1.68e+01,
         1.00e+00]])

In [136]:
np.unique(data[:, 0].astype(np.int))

array([1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810,
       1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821,
       1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832,
       1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843,
       1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854,
       1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865,
       1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876,
       1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887,
       1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898,
       1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909,
       1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920,
       1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931,
       1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942,
       1943, 1944, 1945, 1946, 1947, 1948, 1949, 19

#### Exercise: Calculate the mean temperature of mid-days on February in 1984

In [144]:
year_mask = data[:,0]==1984
month_mask = data[:,1]==2
#data[year_mask & month_mask].shape
data[year_mask & month_mask , 4].mean()

-1.7344827586206901

## Processing large NumPy arrays with memory mapping

In [145]:
mm_w = np.memmap('small_test.mmap', shape=10, dtype=np.float32, mode='w+')
print(mm_w)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Scipy Sparse Matrices

In [147]:
X = np.random.random((10, 5))
X[X < 0.7] = 0
print(X)

[[0.7686481  0.         0.         0.79701936 0.        ]
 [0.79942834 0.97542865 0.         0.97879362 0.9605516 ]
 [0.         0.98937074 0.         0.71930278 0.        ]
 [0.         0.         0.         0.87156029 0.        ]
 [0.         0.         0.         0.91148974 0.        ]
 [0.86310035 0.         0.         0.         0.99533964]
 [0.87050129 0.73214504 0.         0.         0.        ]
 [0.         0.85121312 0.77167542 0.         0.        ]
 [0.         0.         0.72304995 0.         0.87567481]
 [0.         0.         0.         0.         0.        ]]


In [148]:
from scipy import sparse

# turn X into a csr (Compressed-Sparse-Row) matrix
X_csr = sparse.csr_matrix(X)
print(X_csr)

  (0, 0)	0.7686480996671402
  (0, 3)	0.797019363284933
  (1, 0)	0.7994283382098339
  (1, 1)	0.9754286457315555
  (1, 3)	0.9787936180406174
  (1, 4)	0.9605516033474665
  (2, 1)	0.9893707441666922
  (2, 3)	0.719302779067033
  (3, 3)	0.8715602897314557
  (4, 3)	0.9114897373724984
  (5, 0)	0.8631003508281431
  (5, 4)	0.9953396384238361
  (6, 0)	0.8705012910100046
  (6, 1)	0.7321450393469999
  (7, 1)	0.8512131227284023
  (7, 2)	0.7716754220913914
  (8, 2)	0.7230499455358922
  (8, 4)	0.8756748058425039


In [149]:
# Sparse matrices support linear algebra:
y = np.random.random(X_csr.shape[1])
z1 = X_csr.dot(y)
z2 = X.dot(y)
np.allclose(z1, z2)

True

## Ubiquitous NumPy

I called this notebook **ubiquitous numpy** as the main goal of this section is to show examples of **how much is the impact** of NumPy over the Scientific Python Ecosystem.

Later on, see also this **extra** notebook: [Extra Torch Tensor](extra_torch_tensor.ipynb) - _Requires PyTorch_